#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = "{{ .Shell }} in {{ .Folder }}"

[[blocks]]
  type = "prompt"
  alignment = "left"

  [[blocks.segments]]
    type = "session"
    style = "plain"
    foreground = "p:yellow"
    template = " {{ if .SSHSession }}\ueb39{{ end }} "

  [[blocks.segments]]
    type = "os"
    style = "plain"
    foreground = "p:blue"
    template = " {{ .Icon }} {{ .HostName }} "

  [[blocks.segments]]
    type = "session"
    style = "plain"
    foreground = "p:green"
    template = " \uf2c0 {{ .UserName }} "

  [[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "p:cyan"
    template = "  {{ path .Path .Location }}"

[secondary_prompt]
  background = "transparent"
  foreground = "p:white"
  template = " $"

[transient_prompt]
  foreground = "p:yellow"
  template = " {{ .Folder }} $ "

[palette]
  black   = "#585858"
  blue    = "#ffaf00"
  cyan    = "#00afaf"
  green   = "#afd700"
  magenta = "#ffaf00"
  red     = "#5faf5f"
  white   = "#5f8787" 
  yellow  = "#af87d7"
#[palettes]
#  template = "normal"
#  list = [
#    normal = {
#      black   = "#1c1c1c"
#      blue    = "#5fafd7"
#      cyan    = "#d7875f"
#      green   = "#5faf00"
#      magenta = "#808080"
#      red     = "#af005f"
#      white   = "#d0d0d0"
#      yellow  = "#d7af5f"
#    },
#    bright = {
#      black   = "#585858"
#      blue    = "#ffaf00"
#      cyan    = "#00afaf"
#      green   = "#afd700"
#      magenta = "#ffaf00"
#      red     = "#5faf5f"
#      white   = "#5f8787" 
#      yellow  = "#af87d7"
#    }
#  ]
